# Generated by Django 5.2.6 on 2025-09-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_ventadiaria_pedido_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
