# Generated by Django 5.2.6 on 2025-09-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_pedido_confirmado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
