# Generated by Django 5.2.6 on 2025-09-09 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_pedido_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
    ]
