# Generated by Django 5.2.6 on 2025-09-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_remove_pedido_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VentaDiaria',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='total',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
