# Generated by Django 5.2.6 on 2025-09-09 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_ventadiaria_remove_pedido_cliente_pedido_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='atendido',
            field=models.BooleanField(default=False),
        ),
    ]
