# Generated by Django 5.2.6 on 2025-09-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_alter_pedido_mesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoitem',
            name='observaciones',
            field=models.TextField(blank=True, default='con todo'),
        ),
    ]
