# Generated by Django 5.2.6 on 2025-09-13 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_pedidoitem_observaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoitem',
            name='observaciones',
        ),
    ]
