# Generated by Django 5.2.6 on 2025-09-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_remove_pedidoitem_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoitem',
            name='observaciones',
            field=models.CharField(default='con todo', max_length=255),
        ),
    ]
