# Generated by Django 5.2.6 on 2025-09-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_pedidoitem_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoitem',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('preparacion', 'En preparación'), ('listo', 'Listo'), ('agregado', 'Agregado al pedido')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
