# Generated by Django 5.2.6 on 2025-09-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_pedidoitem_estado_alter_pedidoitem_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoitem',
            name='estado',
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
