# Generated by Django 5.2.6 on 2025-09-13 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_pedidoitem_atendido_pedidoitem_surtido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoitem',
            name='atendido',
        ),
        migrations.RemoveField(
            model_name='pedidoitem',
            name='surtido',
        ),
    ]
