# Generated by Django 5.2.6 on 2025-09-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_remove_pedidoitem_atendido_remove_pedidoitem_surtido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoitem',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('preparacion', 'En preparación'), ('entregado', 'Entregado')], default='pendiente', max_length=20),
        ),
    ]
