# Generated by Django 5.2.6 on 2025-09-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0019_remove_pedido_atendido_remove_pedido_entregado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='atendido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
    ]
