# Generated by Django 5.2.6 on 2025-09-13 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0020_pedido_atendido_pedido_entregado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='atendido',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='entregado',
        ),
    ]
