# Generated by Django 5.2.6 on 2025-09-13 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0022_pedido_atendido_pedido_entregado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoitem',
            name='estado',
        ),
    ]
