# Generated by Django 5.2.6 on 2025-09-13 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0023_remove_pedidoitem_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoitem',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
