# Generated by Django 5.2.6 on 2025-09-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0024_pedidoitem_confirmado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoitem',
            name='atendido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='surtido',
            field=models.BooleanField(default=False),
        ),
    ]
