# Generated by Django 5.2.5 on 2026-06-08 20:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0027_cortesia_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('unidad', models.CharField(default='pieza', max_length=30)),
                ('existencia', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('minimo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('maximo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('activo', models.BooleanField(default=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
                ('notas', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='cantidad_descontar',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='producto_almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_menu', to='menu.productoalmacen'),
        ),
        migrations.AddField(
            model_name='productoalmacen',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='menu.proveedor'),
        ),
        migrations.CreateModel(
            name='IngresoMercancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('referencia', models.CharField(blank=True, max_length=120)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('producto_almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos', to='menu.productoalmacen')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos', to='menu.proveedor')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='productoalmacen',
            unique_together={('proveedor', 'nombre')},
        ),
    ]
