# Generated by Django 5.2.5 on 2026-06-08 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0028_productoalmacen_proveedor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingresomercancia',
            name='costo_unitario',
        ),
    ]
