# Generated by Django 5.2.5 on 2026-06-09 17:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0029_remove_ingresomercancia_costo_unitario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('direccion', models.TextField(blank=True)),
                ('notas', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='venta',
            name='estado_pago',
            field=models.CharField(choices=[('saldada', 'Saldada'), ('pendiente', 'Pendiente')], default='saldada', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Deposito o transferencia'), ('fiado', 'Deuda o fiado')], default='efectivo', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='saldo_pendiente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='CajaMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('venta', 'Venta'), ('abono', 'Abono de deuda')], max_length=20)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Deposito o transferencia'), ('fiado', 'Deuda o fiado')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion', models.CharField(blank=True, max_length=180)),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='menu.venta')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='menu.cliente')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='menu.cliente'),
        ),
    ]
